name: Deploy an application

on:
  push:
    branches: [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/deployment.yml'

env:
  DOTNET_VERSION: 7.0.x
  OUTPUT_DIRECTORY: ./output


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:

    - name: Login to the Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up a .NET environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Checkout a repository
      uses: actions/checkout@v3

    - name: Build a project
      run: dotnet build ./src/Tibres/Tibres.csproj --configuration Release --output ${{ env.OUTPUT_DIRECTORY }}

    - name: Deploy a function app
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.APPLICATION_NAME }}
        package: ${{ env.OUTPUT_DIRECTORY }}

    - name: Log out from the Azure
      if: success() || failure()
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
